<a href="https://colab.research.google.com/github/humeracode/18/blob/main/DSCM21L5A1_Churn_Modelling_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install -q keras

### **1. Import Necessary Libraries**

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

### **2. Import Dataset**

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Churn_Modelling.csv to Churn_Modelling.csv


In [ ]:
df = pd.read_csv('Churn_Modelling.csv')
df.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [ ]:
df.describe()

RowNumber    CustomerId  ...  EstimatedSalary        Exited
count  10000.00000  1.000000e+04  ...     10000.000000  10000.000000
mean    5000.50000  1.569094e+07  ...    100090.239881      0.203700
std     2886.89568  7.193619e+04  ...     57510.492818      0.402769
min        1.00000  1.556570e+07  ...        11.580000      0.000000
25%     2500.75000  1.562853e+07  ...     51002.110000      0.000000
50%     5000.50000  1.569074e+07  ...    100193.915000      0.000000
75%     7500.25000  1.575323e+07  ...    149388.247500      0.000000
max    10000.00000  1.581569e+07  ...    199992.480000      1.000000

[8 rows x 11 columns]

**Conclusion -**
1. Dataset Shape - (10000, 14)
2. Numerical features - 11
3. Categorical features - 3
4. Null Values - 0

### **3. Data Preprocessing**

#### **3.1. Label Encoding**

In [ ]:
from sklearn.preprocessing import LabelEncoder
lb = LabelEncoder()

In [ ]:
df['Geography'] = lb.fit_transform(df['Geography'])
df['Gender'] = lb.fit_transform(df['Gender'])

In [ ]:
df

RowNumber  CustomerId    Surname  ...  IsActiveMember  EstimatedSalary  Exited
0             1    15634602   Hargrave  ...               1        101348.88       1
1             2    15647311       Hill  ...               1        112542.58       0
2             3    15619304       Onio  ...               0        113931.57       1
3             4    15701354       Boni  ...               0         93826.63       0
4             5    15737888   Mitchell  ...               1         79084.10       0
...         ...         ...        ...  ...             ...              ...     ...
9995       9996    15606229   Obijiaku  ...               0         96270.64       0
9996       9997    15569892  Johnstone  ...               1        101699.77       0
9997       9998    15584532        Liu  ...               1         42085.58       1
9998       9999    15682355  Sabbatini  ...               0         92888.52       1
9999      10000    15628319     Walker  ...               0         38190.78       0

[10000 rows x 14 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  int64  
 5   Gender           10000 non-null  int64  
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(11), object(1)
memory usage: 1.1+ MB


#### **3.2. Feature Selection**

In [ ]:
df = df.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)

In [ ]:
df.shape

(10000, 11)

#### **3.3. Train Test Split**

In [ ]:
y = df.pop('Exited')
X = df

In [ ]:
X.shape

(10000, 10)

In [ ]:
y.shape

(10000,)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

#### **3.4. Feature Scaling**

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [ ]:
X_train

array([[ 0.16958176,  1.51919821, -1.09168714, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [-2.30455945,  0.3131264 ,  0.91601335, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [-1.19119591, -0.89294542, -1.09168714, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [ 0.9015152 , -0.89294542,  0.91601335, ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-0.62420521,  1.51919821, -1.09168714, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [-0.28401079,  0.3131264 , -1.09168714, ...,  0.64259497,
        -1.03227043,  0.32472465]])

### **4. Model Building**

In [ ]:
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LeakyReLU, PReLU, ELU
from keras.layers import Dropout

#initialize the ANN
classifier = Sequential()

# Add the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'he_uniform',activation='relu',input_dim = 10))

# Add the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'he_uniform',activation='relu'))

# Add the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'glorot_uniform', activation = 'sigmoid'))

# Compile the ANN
classifier.compile(optimizer = 'Adamax', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
model_history=classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

# list all data in history
classifier.summary()
#total params are total number of weights and biases


Epoch 1/100
800/800 [==============================] - 14s 1ms/step - loss: 0.6171 - accuracy: 0.7020
Epoch 2/100
800/800 [==============================] - 1s 1ms/step - loss: 0.5117 - accuracy: 0.7917
Epoch 3/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4891 - accuracy: 0.7918
Epoch 4/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4755 - accuracy: 0.7948
Epoch 5/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4691 - accuracy: 0.7957
Epoch 6/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4574 - accuracy: 0.7956
Epoch 7/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4453 - accuracy: 0.7997
Epoch 8/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4444 - accuracy: 0.7941
Epoch 9/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4340 - accuracy: 0.8001
Epoch 10/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4335 - accur

### **5. Model Evaluation**

In [ ]:
# Predict the Test set results
Y_pred = classifier.predict(X_test)
Y_pred

array([[0.24071875],
       [0.31331962],
       [0.22490042],
       ...,
       [0.15479413],
       [0.13188156],
       [0.17853644]], dtype=float32)

In [ ]:
Y_pred = (Y_pred > 0.5)

In [ ]:
Y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [ ]:
# Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, Y_pred)
print(cm)

[[1533   62]
 [ 213  192]]


In [ ]:
# Calculate the Accuracy
from sklearn.metrics import accuracy_score
score=accuracy_score(Y_pred,y_test)

In [ ]:
print(score)

0.8625
